name = "buildervibescriptonline"
main = "src/worker.js"
compatibility_date = "2024-06-20"

[vars]
# Optional: defaults; secrets will override where appropriate

[[kv_namespaces]]
binding = "VIBESCRIPT_SETTINGS"
id = "REPLACE_WITH_SETTINGS_NAMESPACE_ID"

[[kv_namespaces]]
binding = "VIBESCRIPT_PROJECTS"
id = "REPLACE_WITH_PROJECTS_NAMESPACE_ID"
