name = "buildervibescriptonline"
main = "worker.js"
compatibility_date = "2024-11-01"
workers_dev = true

# Replace the ids below with your real KV Namespace IDs from Cloudflare.
# Find them here: https://dash.cloudflare.com/abd03f1ef831687def8eb96cda0389a0/workers/kv/namespaces
kv_namespaces = [
  { binding = "VIBESCRIPT_SETTINGS", id = "REPLACE_WITH_vibescript_settings_ID" },
  { binding = "VIBESCRIPT_PROJECTS", id = "REPLACE_WITH_vibescript_projects_ID" }
]
